### ISSUE TITLE
photos Chorges

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#101]
Chef,
Elles ne sont pas dans "Pics"

**Comment by llauner** [comment]
C'est normal, elles ne sont pas supposées être dans Pics/  ;)
C'est le fichier champs_des_alpes, donc elles sont dans Pics_champs_des_alpes

**Comment by delta217** [comment]
Moi pas comprendre...:

![image](https://github.com/planeur-net/outlanding/assets/154979750/5f4cd25c-1412-4d49-b95d-e582e16b8512)

le txt fait bien référence à Pics.
Et je n'ai pas de photos de Chorges sur XCSoar ?

**Comment by llauner** [comment]
Dans le repo les images de chorge sont dans Pics_champs_des_alpes
Le Zip contenant tout est combined_guide+champs.xcsoar.zip
Dans ce zip les 2 fichiers sont concatenes, et toutes les images copiees dans le meme repertoire Pics/
Il faut que tu mettes a jour ton repertoire XCSoar avec ce qu'il y a dans le zip.
Je viens de verifier il y a bien chorge dans le dernier zip

**Comment by delta217** [comment]
Pu...., alors, si çà concatene dans mon dos sans rien dire...!
