### ISSUE TITLE
Graphisme des cols

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#103]
Je trouve que le graphisme (que je vois sur mon XCsoar) est nul : on distingue à peine une montagne d'un col.
Pas moyen d'avoir le graphisme type SeeYou, un truc qui ressembe à = ?

**Comment by llauner** [comment]
Ca c'est fige dans XCSoar.
Tu peux faire une issue sur le github, quelques fois c'est pris en compte...
https://github.com/XCSoar/XCSoar/issues

**Comment by delta217** [comment]
Remplacé 6 col par 14 pont, et çà donne çà 👍 

![cols](https://github.com/planeur-net/outlanding/assets/154979750/2871d0a4-b025-4c7c-bb5f-5d9d55c4ca23)

Bien mieux, non ?

**Comment by llauner** [comment]
Oui mais tu coups c'est le mauvais type de point et dans les autres logiciels ca va pas avoir le bon rendu...
Je pense que la seule solution c'est de réussir a avoir XCSoar qui change son icone...

**Comment by delta217** [comment]
Mais comme je n'utilise aucun autre logiciel..., çà me rend bien service.

**Comment by mlep** [comment]
Si l'on a une meilleure idée de graphisme que https://github.com/XCSoar/XCSoar/blob/master/Data/icons/map_pass.svg , on peut proposer un fichier modifié à XCSoar.

**Comment by llauner** [comment]
Bonne idee, il faut leur proposer un graphisme de col qui est celui utilise pour les ponts (partout ailleurs les cols ressemblent a ca).
Et trouver un autre pour les points.
Du coups on a une chance que ca passe la PR...ou pas...ca depend avec XCSoar...

**Comment by delta217** [comment]
Encore sauvé la boite..., çà compense pour les autres conneries que je fais !

**Comment by mlep** [comment]
Un essai pour un nouveau pont : 
![map_bridge](https://github.com/planeur-net/outlanding/assets/6931104/97557dee-08f1-470b-8911-1575c5db5644)

**Comment by delta217** [comment]
C'est bien, çà ressemble aux ponts des billets en € !

**Comment by llauner** [comment]
Je vous laisse faire la PR XCSoar ou vous voulez que je la fasse ?

**Comment by mlep** [comment]
@llauner J'imagine que le graphique te va.
Je peux faire la PR, mais, en fait, je pensais commencer par une Issue.

**Comment by llauner** [comment]
Faut y aller direct avec la PR je pense.
Faut voir avec @mlep ou il a trouve cette image (libre de droit ?) et s'assurer qu'elle a bien la bonne taille.
Apres je pense qu'il faut aussi mettre en avant que dans tous les autres logiciels les cols sont plutôt symbolises par celui qui est actuellement un pont...

**Comment by mlep** [comment]
L'image est de moi.
OK, je tente une PR directe. Souhaitez-moi bonne chance ! (vu les susceptibilités de qq programmeurs)

**Comment by mlep** [comment]
PR à suivre ici : https://github.com/XCSoar/XCSoar/pull/1334

**Comment by delta217** [comment]
> L'image est de moi.

Est ce que tu peux faire aussi une PR pour la mettre sur les billets de 500 € ???

**Comment by delta217** [comment]
@mlep, 

> github/workflows/build-native.yml / build-windows (pull_request) Failing after 6m

çà veut dire que Mr Windows est pas d'accord ?
Explication ?

**Comment by llauner** [comment]
La pull request est merged: https://github.com/XCSoar/XCSoar/pull/1335
