### ISSUE TITLE
lus la croix haute

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#107]
J'y passerai fin février en allant chercher mon planeur qui sort  de peinture à Grenoble, mais il y a une ligne au 1/3 du champs de Lus la Croix Haute :

![lus_la_croix_haute](https://github.com/planeur-net/outlanding/assets/154979750/f3f54e0c-da82-40e9-aa1c-dba0c5733d4f)

**Comment by llauner** [comment]
Fais signe quand tu vas chez Aerotechnics, je passerai te voir.
C'est quoi comme planeur, il y est deja ?
Voir #109

**Comment by delta217** [comment]
LS3a, S03 qui devient SO5 sur le coup ! Il est en finition pour fin février (PU + 6000h).
