### ISSUE TITLE
Francisation des sommets frontaliers

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#112]
J'ai francisé (nom, FR) les 138 sommets qui marquent la frontière entre l'Italie et la France, depuis le col de Larche jusqu'au mont Dolent.
J'ai donc un fichier (extrait du fichier IT) disponible.
Qu'est-ce que j'en fais ?
Je puis assez facilement l'ajouter au fichier FR (il y aura sans doute quelques doublons).
Par contre, s'il fallait les retirer du fichier IT, c'est plus délicat, car j'ai découpé le fichier IT à 1574 lignes pour pouvoir travailler plus facilement.
@llauner , instructions ?

**Comment by llauner** [comment]
Salut @delta217 
Eh beh...ca peut être complique...
C'est vraiment frontière ou c'est en Italie ? parce que si c'etait dans le fichier IT a priori c'etait Italien non ?

Si c'est vraiment frontière on peut les ajouter dans le fichier FR, mais alors il faut les supprimer de IT sinon ca va faire doublon quand le fichier agrégateur est généré.

Ce qu'il serai bien c'est d'ajouter le tag #landmark pour le sommets reference. Et ajouter a cote le nom Italien également.

**Comment by delta217** [comment]
Hello,
Je vais vérifier avec une carte IGN, mais à priori, le Brec de Chambeyron, le Grand Glaiza, la tête de Moïse, le Mont Blanc, le mont d'Ambin, la Scolette, le Dolent (point triple France/Italie/Suisse), etc..., c'est bien en France. Il y en a un paquet dans la massif du Mont Blanc, ils ont détaillé toutes les aiguilles et autres pointes. Je vais voir pour ajouter le nom italien dans la description, le cas échéant.
J'ai du temps, ma fille arrive dans 3/4h à la maternité...!

**Comment by delta217** [comment]
J'ai fait toute la frontière..., il en reste 130 :

![image](https://github.com/planeur-net/outlanding/assets/154979750/dcc19648-96d1-4dc3-9ae3-8e678a85046a)

J'ai mis tous les noms italiens dans la description.
Deux sommets aux coordonnées erronées, mais sans importance (à supprimer sans doute).
En bon français, j'ai considéré que le le mont Blanc de Courmayeur était en France (puisque nous avons un conflit frontalier avec les Italiens sur le sujet..., ce dont témoigne la cartographie OTM) : 

![courmayeur](https://github.com/planeur-net/outlanding/assets/154979750/de279f4c-67f0-4125-be38-23d96a7c1981)

**Comment by delta217** [comment]
Exemple : 

![image](https://github.com/planeur-net/outlanding/assets/154979750/b4869826-c7be-4ec4-87c6-79d1f38f78ef)

**Comment by llauner** [comment]
Ok, alors il faut maintenant:
- Supprimer les points du fichier IT
- Ajouter les points au fichier FR

Tu remets ca dans l'ordre alphabetique avec SeeYou, et tu fais la PR :)

**Comment by delta217** [comment]
Pour ajouter les points frontaliers dans FR, je vois assez bien : copier, trier dans seeyou, et basta...
Pour les supprimer, je pense ajouter les points frontaliers dans IT, trier par latitude dans seeyou, supprimer les deux dont les coordonnées coïncident.
Tu en penses quoi ?
Au préalable, déclarer des landmarks comme il faut, voire supprimer quelques pointt superflus.

**Comment by delta217** [comment]
déclaré  36 landmarks à peu près répartis

**Comment by delta217** [comment]
En pratique : 
- je télécharge FR 
- j'ajoute dans seeyou les points frontière et trie par ordre alphabétique
- et ensuite ? je fais quoi fu fichier augmenté ?

**Comment by llauner** [comment]
Tu remplaces le fichier FR par celui dans lequel tu as fait des modifications.
Tu supprimes aussi les points du fichier IT qui sont passes dans le FR.

Du coups ca devient plus facile d'utiliser un outil type SourceTree ou gitKraken, l'utilisation de l'interface web a ses limites.

**Comment by llauner** [comment]
> déclaré 37 landmarks à peu près répartis

Il faut que ce soient vraiment des landmark par contre = des noms utilises par les velivoles pour se reperer (que cela soit un vrai nom ou un nom velivole),

**Comment by delta217** [comment]
consolidé les sommets frontières avec FR : une vingtaine de doublons supprimés, surtout dans le nord.
reste le plus long, consolider avec IT, et supprimer...

**Comment by delta217** [comment]
consolidé les sommets IT sans les frontières. Le truc, c'était de trier par altitude pour les dégommer les uns après les autres. Ma fille est toujours en salle de travail, comme on dit...

**Comment by llauner** [comment]
Voilà. 
Ça va rien te dire ça va te dire que tu as fait des changement et tu feras un commit. 
Ou si il y a rien pour uploaded tu modifie le fichier et tu fais un copier / coller avec le nouveau.  
Au travail ! 😉

**Comment by delta217** [comment]
Bien chef !

**Comment by delta217** [comment]
Je garde au chaud le fichier des sommets frontaliers au cas où ?

**Comment by llauner** [comment]
> Je garde au chaud le fichier des sommets frontaliers au cas où ?

Bof...je vois pas a quoi ca peut servir de les isoler du reste...mais rien ne t'empêche de mettre ca dans une branche et de la garder si tu veux.
