### ISSUE TITLE
Francisation des sommets frontaliers, partie Sud, et intégration dans FR ?

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#114]
Le premier jet - oh combien mouvementé ! - portait sur la partie col de Larche - Mont Dolent.
Maintenant qu'on a compris les petites vacheries que nous réservait SeeYou, fait-on la partie Sud ?
NB : je m'étais lancé sur la partie nord parce qu'elle me concernait...

**Comment by llauner** [comment]
En avant...
Apres on pourra faire la meme chose avec CH

**Comment by delta217** [comment]
C'est comme si c'était fait, patron...
Et donc, SeeYou ne nous fait plus de misère ?
Quand bien même il en ferait, on sait maintenant que l'écart maximum est 0.5" x racine de 2 = 22 m

**Comment by delta217** [comment]
Bon, j'ai 65 sommets sous la main.
Pour les supprimer d'Italie, çà risque d'être galère, car il doit y avoir une palanquée de sommets à ces altitudes, et c'était comme cela que je procédais (pas beaucoup de sommets à plus de 4500 m...!).

**Comment by delta217** [comment]
Patron, j'ai un problème, il y a des sommets "français" en Italie : 

![image](https://github.com/planeur-net/outlanding/assets/154979750/c840c514-f431-440e-ac0f-99099e602fbd)

**Comment by llauner** [comment]
> Patron, j'ai un problème, il y a des sommets "français" qui trainent encore en Italie :

Bouges pas je les supprimes du fichier IT, en regardant au passage qu'ils sont dans le fichier FR...

**Comment by llauner** [comment]
> Bon, j'ai 65 sommets sous la main. Pour les supprimer d'Italie, çà risque d'être galère, car il doit y avoir une palanquée de sommets à ces altitudes, et c'était comme cela que je procédais (pas beaucoup de sommets à plus de 4500 m...!).

Ah ben il va falloir les supprimer pourtant.
En faisant un copier / rechercher dans le fichier FR par code par exemple ?

**Comment by llauner** [comment]
> > Patron, j'ai un problème, il y a des sommets "français" qui trainent encore en Italie :
> 
> Bouges pas je les supprimes du fichier IT, en regardant au passage qu'ils sont dans le fichier FR...

C'est fait...le fichier IT ne contient plus de FR

**Comment by mlep** [comment]
Une idée pour faciliter le traitement des sommets aux frontières, et en particulier leur déduplication :
- partir du fichier mountain_peaks_FR_CH_IT.cup (oui je sais, c'est une fusion automatique)
- marquer (dans SeeYou) les sommets en trop
- avec un script, supprimer ces sommets dans les fichiers sources (mountain_peaks_CH.cup et mountain_peaks_IT.cup).

**Comment by llauner** [comment]
Bah a ce moment plutot faire un truc qui prend 2 fichiers et qui:
- Regarde les paires de sommets qui sont a moins de 500m (ca doit etre le meme)
- Affiche les paires suspectes
- Propose d'effacer dans un des deux fichier l'entree en double.

Et du coups on fait ca avec FR+IT, FR+CH, CH+IT

Je peux faire un truc en C#, en Python, ou en NodeJS. Bien envie de faire du C# ca fait longtemps...
Qu'en dis tu >

**Comment by mlep** [comment]
Aucune idée du meilleure language... :wink: 
Mais meilleure idée que la mienne !

**Comment by llauner** [comment]
@mlep @delta217 
Bon alors j'ai un morceau de code qui compare deux fichiers et qui ressort les points qui sont a moins de xx metres l'un de l'autre.
Et du coups en essayant avec FR et CH ca sort bien dans les 35 points qui sont en double: Ils ont aussi le meme nom !
Donc ce que je vais faire:
- Virer du fichier CH les points qui sont deja dans FR
Et apres je fais la meme chose pour IT.

Ca vous va ?

**Comment by delta217** [comment]
Maitre vous êtes trop fort...,
Du coup, je ne fais rien avec mes 63 points frontières qui étaient en Italie, ou pas ?

Hier, la montagne, mais autrement (un col sans nom ! on va l'appeler col Sierra05 dans le fichier !): 

![20240204_13](https://github.com/planeur-net/outlanding/assets/154979750/0ad4ff23-4568-48a4-ab7b-2fa90de21a79)

**Comment by delta217** [comment]
A condition de monter à 1600m...
Les randos strictement locales (Céüse, Pic de Gleize,..) sont totalement imprataicables.

**Comment by delta217** [comment]
> Je peux faire un truc en C#, en Python, ou en NodeJS. Bien envie de faire du C# ca fait longtemps... Qu'en dis tu ?

J'étais premier prix de latin, pas fait de grec, ni d'hébreu, mais quand même un peu de FORTRAN IV... 
Donc, je laisse volontiers çà aux experts !
