### ISSUE TITLE
Piste 02/20 vs 020/200

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#28]
Je pense que si le format .cup impose d'indiquer le QFU en degrés, la règle aéronautique est d'utiliser le QFU en dizaine de degrés : "Sierra Fox en finale pour la 02", et non pas "020".
Donc, dans le descriptif entre guillemets, on devrait généraliser le 02/20 plutôt que le 020/200.

**Comment by llauner** [comment]
J'ai réfléchi a la question, et je pense qu'il faut maintenir les degres de partout pour plusieurs raisons. Il faut avoir le moins de gymnastique mentale dans le planeur, donc:
- Quand on regarde les details d'un point SeeYou Navigator ou XCSoar ont unchamps "runway" qui indique deja par exemple 02 ou 02/20 donc l'information du QFU est la.
- Quand on regarde la description du champs on a la "traduction" en degres, avec 3 chiffres qui ne laissent aucun doute sur le fait que ce sont bien des degres et non des QFU
- Pour les champs j'ai du mal a parle de QFU etant donne que ce n'est pas une piste, il me semble plus logique de parler de "direction", donc en degres.

Du coups j'ai vu qu'il restait encore des QFU (et non des degres) dans certaines lignes...je vai corriger cela ;)
