### ISSUE TITLE
Cime de Grand Vallon - ligne 2160

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#38]
Les coordonnées indiquées sont celles de la Pointe de Paumont, ou Pointe du Vallon. L'altitude est 3171m.
Il ne faudrait pas utiliser la pointe du Vallon, car il y en a une autre en Vanoise (dont les coordonnées sont justes).
La Cime du grand vallon est
"C. du Gr. Vallon",C.duGlon,FR,4508.750N,00642.317E,3129.0m,7,,,,,,,

la ligne 2484 Pelouse est fantaisiste.
Il pourrait s'agir de Rocca Verde, dont l'altitude et la longitude seraient cohérentes, mais pas la latitude
"Roccia Verde",Rverde,FR,4507.650N,00643.617E,2852.0m,7,,,,,,,

**Comment by delta217** [comment]
![pointeduvallon](https://github.com/planeur-net/outlanding/assets/154979750/df5811b1-8263-4d53-8ee4-0c858411933c)

**Comment by delta217** [comment]
![rocciaverde1](https://github.com/planeur-net/outlanding/assets/154979750/c6f5f4cc-e69a-4340-a28a-079209ace710)

Ce qui donne çà dans XCSoar

**Comment by llauner** [comment]
Pas de problème, on sait que ce fichier n'est pas tres fiable, donc a nous de le fiabiliser, en commencant par ce qui est autour de chez nous ;)
Donc pas de soucis, tu fais une PR en supprimant ce qui est fantaisiste et en mettant un autre point plus représentatif.
Merci

**Comment by llauner** [comment]
Plus d'actualité avec le nouveau fichier moutnain_peaks_FR.cup
