### ISSUE TITLE
Montagne des Alpes : une source

### ISSUE THREAD

**Issue by mlep** [planeur-net/outlanding#41]
Dans le README.md, il est indiqué que la source du fichier des montagnes des Alpes était à retrouver.
La source serait-elle ici ? :  [https://github.com/XCSoar/xcsoar-data-content/issues/107](https://github.com/XCSoar/xcsoar-data-content/issues/107)

**Comment by llauner** [comment]
Bonjour @mlep 
Ce n'est pas cette source, mais celle ci me semble tres bien. Elle a été auto générée, et donc ne semble pas avoir de noms fantaisiste.
Je me demande si je ne vais pas supprimer le fichier montagnes_des_alpes et remplacer par un lien vers les fichiers que tu indiques...
Il n'y a pas trop d'interet a refaire la meme chose que ce qui existe et en moins bien !
Qu'en dis tu ?
@delta217 qu'en dis tu ?

**Comment by snip** [comment]
Il n'y a pas des noms de montagnes qui ont un nom purement vélivole ?

**Comment by llauner** [comment]
> Il n'y a pas des noms de montagnes qui ont un nom purement vélivole ?

Si...il y en a plein.
On pourrait récupérer le fichier et renommer les montagnes qui ont un nom vélivole. On pourrait au passage en dégager un certain nombre, la ou la densité de nom est trop importante et pas vraiment intéressante...
En tous cas ces fichiers me semblent être une meilleure base que ce que l'on a actuellement dans le repo..
 C'est peut etre une meilleure approche qu'en pensez vous ? @snip @mlep @delta217

**Comment by mlep** [comment]
En complément du commentaire de @snip :
Le remplacement par un lien ne permettra pas d'adapter le fichier. Or, ce fichier est une extraction automatique de sommets, et est incomplète : par exemple (pas pris au hasard :-) ), je crois qu'il n'y a pas de Saint-Eynard. De mémoire, il y a aussi quelques lignes mals formées.
De plus, le fichier lié peut disparaitre du jour au lendemain (dommage que l'auteur n'est pas souhaité libérer ses scripts !)
Enfin, le fichier n'a pas été mis à jour depuis 2021, alors qu'OSM a dû s'enrichir en nom de sommets depuis.
Et, effectivement, on pourrait commencer par dé-densifier les noms de montagne enregistrés (je l'avais d'ailleurs fait à la main pour mon propre usage, en ne gardant que le plus haut point par km²  --- sans plus réfléchir).
Et remplacer Gipfel par Sommet.
Bref, le fichier est améliorable.

**Comment by llauner** [comment]
Bon...je pense que je vais copier le nom des montagnes pour FR, CH, IT.
Et l'idée sera donc de "rationaliser" le fichier FR en premier = 
- Epurer pour ne garder que les nom intéressants et supprimer lorsque les noms sont trop proches.
- Renommer a la sauce vélivoles les montagnes connues (Authon, Lucy, ...) 

Au besoin je pourrai faire une concatenation automatique de FR+CH+IT
On y va comme ca ? :)

**Comment by mlep** [comment]
Oui ! Tu nous mets le fichier sur le dépôt, que l'on travaille dessus ?

Est-ce que l'on propose aussi à la communauté un fichier Pyrénées ?

**Comment by llauner** [comment]
> Oui ! Tu nous mets le fichier sur le dépôt, que l'on travaille dessus ?
OK je fais ca..
Je vais dégager le commentaire "Gipfel", on sait que c'est un sommet vu qu'il y a le type CUP
Je pense aussi dégager l'altitude qui se trouve entre parentheses dans le nom...c'est déjà present dans le .cup et ca rend le truc moins lisible sur le fond de carte

> Est-ce que l'on propose aussi à la communauté un fichier Pyrénées ?
Les Pyrenees ? c'est pas des vraies montagnes :)
Oui je vais ajouter ca, on verra si ca intéresse.

Pour le reste je vais sauvegarder quelques fichiers de ce site, et ajouter la source en reference.

**Comment by llauner** [comment]
C'est fait !
Je crois que la premiere des choses a faire c'est de limiter la densité des noms de montagnes dans nos regions, il y a trop de noms !
Ensuite modifier pour avoir les noms velivoles...

**Comment by delta217** [comment]
Déjà, il y l'Albaron...
Donc on est reparti pour un tour !

**Comment by mlep** [comment]
@llauner Je peux refaire ma manip pour garder le plus haut point sur un km². Je m'y lance (ou quelqu'un d'autre) ?

**Comment by delta217** [comment]
Il n'y a pas ma maison, mais la colline que j'emprunte en VTT pour aller acheter le pain !
Sans rire, je n'ai pas vu de cols, ce qui me semble un inconvénient majeur. 

![image](https://github.com/planeur-net/outlanding/assets/154979750/1066ba11-2bfc-4e24-b677-426fbe3298a6)

**Comment by delta217** [comment]
J'ai retrouvé le dôme du Grand Fond ! Lequel n'est pas bien loin de l'Albaron. Et l'Ouille d'Arbéron.
Ce qui semble indiquer que ce fichier est bien foutu, et juste.

![image](https://github.com/planeur-net/outlanding/assets/154979750/a014dc4f-1a2b-4a0e-8d7e-5c0df334daa5)

**Comment by llauner** [comment]
@delta217 
Typiquement le petit col vers gap...il serait pas un peu bas pour nous intéresser ? et si on dégageait tout ce qui est au dessous de...1000m ?
Ta question sur pic de, sommet de...je comprends pas..a priori il ya des trucs qui s'appellent pic de xxx et d'autres sommets de yyy, ca doit etre le nom officiel vu la source. Je pense qu'on peut laisser comme ca non ?

**Comment by llauner** [comment]
@mlep 
C'est une bonne idée, mais est ce qu'on est certain que le plus haut est généralement celui que l'on connait / utilise ?
Je sais pas quel est le bon maillage, 1km2 ca semble petit, 10 c'est peut être trop gros...
Le problème de le faire a la main c'est qu'on voit pas facilement le plus haut...et c'est laborieux..

Tu peux peut etre faire des essais, et voir quel maillage semble acceptable, et tu nous dis en nous passant le resultat pour qu'on puisse voir ?
Penses bien a faire un Rebase ou un Pull avant de prendre le fichier source...

**Comment by delta217** [comment]
@llauner, Ah, mais c'est que j'ai vu un parapentiste passer le col de St Mens !
Concernant les "sommet de", c'est que çà prend beaucoup de place et masque le nom significatif (cf. Auribeau/Géruen ci-dessus). De ce point de vue, le fichier précédent était pas mal foutu, avec tous les cols qui étaient "c-xxxxx" ou les "montagne de" transformées en "Mgne de". A regarder la densité et le choix des sommets, le fichier précédent était certainement un fichier vélivole.

**Comment by llauner** [comment]
@delta217 
Ok je comprends pour sommet et pic de... tu as raison. Alors...je proposerais:
Montagne de xx -> Mtgn de xx
Mont xx -> Mnt xx
Pic de xx -> Pic xx
Pointe xx -> Pnt xx
On commence comme ca ?

**Comment by delta217** [comment]
Bon, je sais faire.... je peux m'y coller si le grand chef le souhaite :

![image](https://github.com/planeur-net/outlanding/assets/154979750/964d928c-476e-4690-85a4-39308f7c9249)

**Comment by delta217** [comment]
[mountain_peaks_2FR.txt](https://github.com/planeur-net/outlanding/files/13877289/mountain_peaks_2FR.txt)
Je te l'envoie en txt, sinon çà passe pas.
Ce que je n'ai pas fait, mais çà me démange, c'est de supprimer les "le..." et les "la...", mais pas les "l'..."
Dans les textes courts, il y a parfois des trucs pas significatifs, type "tête de".

**Comment by llauner** [comment]
@delta217 
Qu'est ce que tu veux dire par "ca passe pas" ? Tu peux pas modifier, faire un commit et faire la PR ?

**Comment by delta217** [comment]
Dans ce thread - comme on dit - le .cup ne passent pas, donc je l'ai passé en .txt.
Le problème, çà va être de sélectionner : idéalement il faudrait pouvoir le faire à l'écran sur XCsoar ? Ou sur un autre logiciel ?
L'autre problème, c'est qu'il va falloir modifier ligne par ligne un paquet de "code" qui ne sont pas significatifs ("tetede").
Avec XCSoar sur PC, quelqu'un sait-il afficher le nom complet ? Je n'ai pas réussi.

**Comment by llauner** [comment]
@delta217 
OK je comprends je pense:
Pour sélectionner visuellement tu peux utiliser SeeYou sur ton PC.

Pour modifier le .cup tu le fait avec un editeur, tu as la version "simple" qui est Notepad++ ou la version améliorée qui est Visual studio code (avec le plugin Rainbow CSV)
Dans l'editeur tu fais un chercher / remplacer et tu fais le remplacement de Montagne de par Mtgn de par exemple...
Tu as fait comment dans le fichier en attachement pour modifier ? ligne par ligne a la main ?

Pour voir toute la ligne dans xcsoar: Config / System / Map Display / Waypoints / Label format = Full name

**Comment by delta217** [comment]
Une version 3 où j'ai supprimé tous les "le", "la", et "les"
[mountain_peaks_3FR.txt](https://github.com/planeur-net/outlanding/files/13878857/mountain_peaks_3FR.txt)
J'ai utilisé le bloc note, tout simplement,

**Comment by delta217** [comment]
La suppression des "le la les" ne me semble pas problématique.
Reste à trouver une sélection à l'écran, ce qui serait génial.

**Comment by llauner** [comment]
@delta217 
En regardant avec XCSoar ou SeeYou Navigator...je suis meme pas certain qu'abréger les noms soit une bonne idee...
Ca reste lisible meme avec toute la ligne.
Par contre il y en a beaucoup...ca c'est vrai.

Utilises SeeYou pour visualier et supprimer, c'est le plus rapide.

**Comment by delta217** [comment]
Ben ya du monde sur le fichier...
Je comprnds pourquoi il y a des terrils !

![image](https://github.com/planeur-net/outlanding/assets/154979750/dc821cee-d03e-4d0a-b08e-079b7fe19d9d)

**Comment by mlep** [comment]
Peut-on décider d'un ordre des tâches à réaliser sur le fichier avant de s'y lancer tête baissée ? parce que sinon, nous risquons de passer du temps sur des choses qui vont passer à la trappe... (par exemple, à mon sens, le nettoyage des noms de sommets se ferait plutôt dans un second temps ; histoire de ne pas nettoyer trop de choses qui disparaitront ensuite).

Je propose : 
1. Fusion des fichiers FR, IT et CH
2. Suppression des zones hors "montagne des Alpes"
3. Dédensification (sélection parmi les sommets proches)
4. Harmonisation des noms de sommet longs
5. Harmonisation des noms de sommets courts
6. Adaptation au vol en planeur (sommets manquants, noms d'usage des sommets)

En gros, ma liste veut aller du plus automatique au plus manuel.

Votre avis ? D'autres tâches ?

**Comment by llauner** [comment]
@mlep @delta217 
Je viens de créer
#54 
#55 
#59 
#56 
#57 
#58 

J'ai pris #54 et #55 vous pouvez vous assigner la tache avant de la faire pour qu'on ne se marche pas sur les pieds.
Je vais commencer par #55 qui est un peu bloquante pour toute le monde...

**Comment by delta217** [comment]
> @delta217 En regardant avec XCSoar ou SeeYou Navigator...je suis meme pas certain qu'abréger les noms soit une bonne idee... Ca reste lisible meme avec toute la ligne.
> 
> Utilises SeeYou pour visualier et supprimer, c'est le plus rapide.

Il faut penser aux gens qui ont des écrans pas trop grands.
Et, par exemple, "sommet de Denjuan", "Denjuan" serait carrément suffisant. 

C'est possible d'avoir Seeyou en standalone sur le PC ?

**Comment by llauner** [comment]
> Il faut penser aux gens qui ont des écrans pas trop grands. Et, par exemple, "sommet de Denjuan", "Denjuan" serait carrément suffisant.

OK, il y a certains trucs comme Sommet de xxx qui peuvent être abrégés. A voir au cas par cas (Sommets de, montagne de...)
Si l'ecran n'est pas trop grand tu fais afficher le code plutot que le nom long, c'est fait pour ca.  Je ne veux pas qu'on fasse du nom un truc a dechiffrer.


> C'est possible d'avoir Seeyou en standalone sur le PC ?

Oui c;est SeeYou:
https://naviter.com/seeyou-makes-you-a-better-pilot/

A ne pas confondre avec SwwYou mobile pour PDA + Oudie 
Et SeeYou Navigator pour Oudie N, Android, iOS

**Comment by delta217** [comment]
Excellent Seeyou (tant que c'est gratuit !).
Par contre, comment transformer un .cup en .xls, sans que toute la ligne  soit dans la même case ? Question de béotien, sans doute...

**Comment by llauner** [comment]
Pas forcement une bonne idee de modifier le .cup avec Excel: quand tu re-sauvegarde il a tendance a ajouter des " je crois..
Sinon pour repondre:
Quand tu fais fichier / ouvrir, il te propose une boite de dialogue et la tu lui dis que le separateur c'est une virgule.

Mais vraiment le plus simple pour modifier en masse un .cup c'est notepad++ ou Visual studio code. Tu fais du rechercher / remplacer c'est plus simple.
Regarde visual studio code, avec l'extension rainbow CSV. Ca te permet meme d'avoir les colonnes alignee pendant que tu edites. Apres tu remet tout en paquet...
![image](https://github.com/planeur-net/outlanding/assets/32835597/21f0a9f7-dda6-42fb-b437-2ab717ffcfeb)

**Comment by delta217** [comment]
En tout cas ce fichier est excellent, j'ai un peu cherché des erreurs, et n'ai rien trouvé.

**Comment by delta217** [comment]
Celui-là, on va le garder aussi !

![image](https://github.com/planeur-net/outlanding/assets/154979750/e1f609b4-9c7a-4c5c-b104-2247952a6ad8)

**Comment by llauner** [comment]
Je ferme le sujet, etant donne que la source est maintenant integree.
Au besoin il y a la partie "discussion" si l'on veut discuter de nouveaux champs a integrer...
