### ISSUE TITLE
Mountain_peaks_FR: Dedensification

### ISSUE THREAD

**Issue by llauner** [planeur-net/outlanding#56]
Supprimer noms de montagnes non significatifs dans les zones trop denses en noms

**Comment by mlep** [comment]
Je prends cette tâche.
(pas trouvé comment me l'assigner)

**Comment by llauner** [comment]
En haut a droite: Assignees.
Je viens de te l'assigner...

**Comment by mlep** [comment]
Merci !
(juste pour info : je peux me dé-assigner, mais pas m'assigner)
