### ISSUE TITLE
Mountain_peaks_FR: Adaptation noms au VaV

### ISSUE THREAD

**Issue by llauner** [planeur-net/outlanding#57]
Adapter les noms de montagnes au Vol a Voile. Par exemple: Authon, ...

**Comment by mlep** [comment]
Et mettre #landmark en commentaire pour les identifier (voir https://github.com/planeur-net/outlanding/pull/70#issuecomment-1888672120).
Exemple : "Arambre",Arambre,FR,4425.812N,00544.711E,1444.0m,7,,,,,,, "#landmark"
(@llauner, tu confirmes le format ?)

**Comment by llauner** [comment]
> "#landmark" (@llauner, tu confirmes le format ?)

Oui ca me semble pas mal. J'avais pense a {landmark} pour une certaine coherence avec le niveau de difficulté des champs...mais l'utilisation et l'endroit ou ca sera utilise n'est pas le meme...donc en avant pour #landmark

**Comment by llauner** [comment]
Voici ce que donne
Type 19= Control/Reporting Point (Dent de Crolles)
Type 18= Marker (St Eynard)
![image](https://github.com/planeur-net/outlanding/assets/32835597/b3f76595-e275-46d0-ac65-b4dd0481df0b)

Je trouve que Control/Reporting point c'est pas mal pour mettre en avant les montagnes les plus utilisées...

**Comment by snip** [comment]
Le type 18 du St Eynard est + dans le style des autres montagne. Donc ca me semble plus approprié (pour les lister tout en les classant dans un type proche que les autres montagnes).

**Comment by llauner** [comment]
Pour les cols, il y a un type spécifique dans le format cup: https://github.com/planeur-net/outlanding/blob/main/doc/SeeYou_CUP_file_format.pdf

Mon point est que si on ajoute #landmark en commentaire, c'est pas evident que ca serve a quelque chose si on ne peut pas le visualiser, si ce n'est que si on regarde le commentaire...d'où l'idée de le mettre en type Control / reporting point.
Ce qui n'est pas totalement faux puisque certes c'est un une montagne (on le sais c'est le fichier des noms de montagnes), mais en plus c'est un "reporting point" dans le sens ou c'est une montagne très connue et utiliser pour indiquer sa position.

Je suis pas trop partisan de faire trop de menage, la version qu'on a me semble pas mal. Typiquement "Chateau Nardent" je l'ai déjà entendu.

**Comment by mlep** [comment]
> Pour les cols, il y a un type spécifique dans le format cup: https://github.com/planeur-net/outlanding/blob/main/doc/SeeYou_CUP_file_format.pdf

Oui, justement : va-t-on mettre un col vélivole avec le même symbole qu'un sommet vélivole ?

> Mon point est que si on ajoute #landmark en commentaire, c'est pas evident que ca serve a quelque chose si on ne peut pas le visualiser, si ce n'est que si on regarde le commentaire...d'où l'idée de le mettre en type Control / reporting point. Ce qui n'est pas totalement faux puisque certes c'est un une montagne (on le sais c'est le fichier des noms de montagnes), mais en plus c'est un "reporting point" dans le sens ou c'est une montagne très connue et utiliser pour indiquer sa position.

Ah. Parce que, dans mon idée, Landmark ne servait qu'à la gestion du fichier, pas à voler.
En vol, j'ai autre chose à faire qu'à me rappeler d'une symbolique: c'est le sommet ou le col le plus proche, je m'y annonce.

> Je suis pas trop partisan de faire trop de menage, la version qu'on a me semble pas mal. Typiquement "Chateau Nardent" je l'ai déjà entendu.

Alors, c'était un mauvais exemple, puisque c'est un sommet vélivole. ;-)

**Comment by llauner** [comment]
> Oui, justement : va-t-on mettre un col vélivole avec le même symbole qu'un sommet vélivole ?

Ah je comprends...j'avais pas pense aux cols comme point de repère...

> Ah. Parce que, dans mon idée, Landmark ne servait qu'à la gestion du fichier, pas à voler. En vol, j'ai autre chose à faire qu'à me rappeler d'une symbolique: c'est le sommet ou le col le plus proche, je m'y annonce.


Mmmm....mouais...sans doute.
Bon on est peut être en train d'essayer d'en faire trop.
Ce que je propose:
On conserve pour tous les points actuels (ils sont déjà passés a travers ton premier filtre).
On fait une passe pour renommer les sommets en sommets velivoles (Authon, ...)
On ajoute #landmark en commentaire des sommets velivoles pour savoir que c'est un sommet velivole, et qu'il ne faut pas y toucher.

**Comment by mlep** [comment]
Pas de la cavale, Pas de la Coche, par ex.

OK. Dans tous les cas, il nous faut ces sommets vélivoles.
Note : on marque aussi comme #landmark les sommets déjà inclus qui sont (aussi) connus des vélivoles.
Et on verra ensuite.

**Comment by mlep** [comment]
Est-ce que l'on considère que l'on a à présent identifié les sommets vélivoles ? (et donc fermer ce sujet) Et que l'on peut donc supprimer les nombreux noms de sommets non vélivoles localisés sur une même crête ?

Ou un appel à la communauté pour venir y contribuer ?

**Comment by llauner** [comment]
Bonne question.
C'est vrai que quand je regarde par exemple le vieux chaillol, je me dis que pic et tete de mal cros peuvent degager.
Avec le cuchon "le barry" peut degager.
Par contre je vois pas "le petit chaillol" qui doit etre purement velivole

Je pense qu'on pourrait lancer un appel pour les noms velivoles et en meme temps supprimer les noms qui sont just a cote et qui ne servent pas de repere (voir exemple au dessus)

**Comment by delta217** [comment]
Non, le petit Chaillol est un vrai sommet, à l'entrée du Valgaudemar, côté sud.
Appellé aussi banc du Peyron.

**Comment by delta217** [comment]
Et la question est : comment en fait pour dédensifier ?

**Comment by llauner** [comment]
> Et la question est : comment en fait pour dédensifier ?

A talent j'ai envie de dire....:)
On va pas trop dédensifier , un petit coups comme ca au passage sur un renommage, comme ici par exemple:
![image](https://github.com/planeur-net/outlanding/assets/32835597/87d1d4b8-56dc-4fa1-b3ce-190e5ae70bbe)

- Je pense qu'on peut degager le pic de mal Cros, il y a la tete de mal Cros juste a cote, et surtout quand on est la on est au "vieux chaillol"...enfin moi je suis au vieux chaillol, c'est a moins d'1km de distance alors...
- Je vais rennomer le petit chailllol et ajouter en landmark...

**Comment by delta217** [comment]
Ouais, je trouve que c'est astronomique quand même.
Je pense que je vais m'en faire un "slim" Alpes.
On peut trier sur les colonnes dans notepad, par exemple ?

![image](https://github.com/planeur-net/outlanding/assets/154979750/62f74926-b473-4a11-81e2-7b23ca35f84f)

**Comment by llauner** [comment]
Tu veux trier sur quel critere ?
Moi je trouve que ca va, on a pas le fichier affiche en permanence de toutes facons...
Je vais essayer d'utiliser l'outil de mlep pour faire une version light an gardant les landmark.
Je pense que la bonne demarche ca serait vraiment de mettre le tag #landmark sur les sommets que l'on souhaite vraiment garder. sinon avoir une version "light" faite a la main c'est ingérable...
Tu voudrais pas plutot ajouter le tag #landmark partout ou tu penses que c'est un sommet a vraiment garder = un point de repere bien connu et utilise des velivoles.

**Comment by delta217** [comment]
Virer tout ce qui est à l'ouest du Rhône, à l'est de Vintimille, au nord du Léman...
Ajouter le tag #landmark , çà peut se faire dans SeeYou ? En payant peut-être (pas encore payé...).
J'ai posé la question de l'icone col dans le forum XCSoar.

**Comment by llauner** [comment]
> Virer tout ce qui est à l'ouest du Rhône, à l'est de Vintimille, au nord du Léman... Ajouter le tag #landmark , çà peut se faire dans SeeYou ?

Oui
Je viens de modifier le soft de @mlep je pense que c'est vraiment la bonne démarche la tag #landmark
Je vais d'ailleurs en ajouter dans le coin de Grenoble...

**Comment by delta217** [comment]
Dans SeeYou, il y a aussi des boulettes : le col de Mirandol par exemple :

![image](https://github.com/planeur-net/outlanding/assets/154979750/24be719e-c6fe-4bc5-b1d6-511c71155ab6)

Et puis virer la tête de la Platasse...

**Comment by delta217** [comment]
C'est quoi l'dée du landmark (j'ai pas tout suivi...).
Ca permet de faire une version épurée ?

**Comment by llauner** [comment]
> Dans SeeYou, il y a aussi des boulettes : le col de Mirandol par exemple :

Alors c'est pas "dans SeeYou" c'est dans un fichier a nous. Mais il n'y a pas de Col de Mirandol dans nos fichiers.
Tu veux dire que c'est dans le fond de carte de SeeYou ? bahh...c'est pas grave ca...


> Et puis virer la tête de la Platasse...
OK je le fais dans ma PR courante...

**Comment by llauner** [comment]
> C'est quoi l'dée du landmark (j'ai pas tout suivi...). Ca permet de faire une version épurée ?

L'idee c'est de rajouter un tag #landmark dans les commentaires afin d'identifier les montagnes qui sont connues de tous (ou des noms velivoles) et qu'il faut absolument garder.
Donc l'idee c'est d'ajouter ces tags la ou il faut, et ensuite on peut passer le fichier a la moulinette de @mlep pour diminuer le nombre de points et faire une version "light" automatiquement.
Meme principe que pour les autres fichiers: on fait l'edition d'un minimum de fichiers, et on génère tout ce qu'on peut automatiquement.
Ca permet de ne pas faire 50x le boulot, et ca permet surtout de ne pas avoir de divergence entre les version = on a une coherence des infos.

**Comment by delta217** [comment]
Tu veux que je prenne des "landmarks" à ajouter ?
Sous quelle forme ? 
Je peux prendre par exemple parcours, Ubaye, Ecrins, Briançonnais, Maurienne.

**Comment by llauner** [comment]
> Tu veux que je prenne des "landmarks" à ajouter ? Sous quelle forme ? Je peux prendre par exemple parcours, Ubaye, Ecrins, Briançonnais, Maurienne.

Allez...en avant...
Prends bien la derniere version, je viens de merger ce que j'avais fait...

**Comment by delta217** [comment]
En pratique, tu fais çà dans seeyou, tu enregistres et après ?
Ou alors, ligne à ligne sur le .cup de github ?

**Comment by llauner** [comment]
Tu supprimes dans SeeYou, tu verifies que les points sont bien dans l'ordre alphabetique, tu sauvegardes en ecrasant l'ancien et a la main tu vas supprimer la derniere ligne avec les ---
Tu regardes apres que la difference entre l'ancien et le nouveau porte bien sur ce que tu as fait, et que tu te retrouves pas avec des lignes etranges, ou que le "version" se trouve pas n'importe ou...

**Comment by delta217** [comment]
> Tu regardes apres que la difference entre l'ancien et le nouveau porte bien sur ce que tu as fait

Et çà, comment ?

**Comment by llauner** [comment]
> Et çà, comment ? 

Ah...ben moi j'utilise [source Tree ](https://www.sourcetreeapp.com/) pour faire mes branch, commit, ... du coups ca me donne la difference avant le commit.
Sinon t'es oblige de faire une sauvegarde du fichier modifie avec un autre nom, de comparer, de corriger au besoin, et ensuite d'ecraser l'ancien
Pour comparer tu as plein d'outils:
https://meldmerge.org/
https://www.perforce.com/products/helix-core-apps/merge-diff-tool-p4merge
https://winmerge.org/

> Et j'ajoute #landmark dans seeyou aussi. Correct ?
Oui c'est le plus simple. Dans les commentaires du point

**Comment by delta217** [comment]
Heuuuu.... je crois que je vais faire une branche chez moi avec le fichier modifié comme d'hab., et après tu check ?

**Comment by llauner** [comment]
Si tu veux, mais regardes quand meme les outils de diff ca peut etre interessant pour voir les differences entres 2 fichiers...

**Comment by delta217** [comment]
le truc, si je met #landmark dans seeyou, il me dit no valid character ?

**Comment by delta217** [comment]
Moi, c'est différent :

![image](https://github.com/planeur-net/outlanding/assets/154979750/ef692f86-7242-4cb0-8ce0-1ed7919d4bb3)

Et je suis bien dans la description :

![image](https://github.com/planeur-net/outlanding/assets/154979750/8d150400-131d-4831-a482-82b6cc160975)

**Comment by llauner** [comment]
Ca c'est SeeYou Cloud
Il faut utiliser la verdion PC:
https://naviter.com/download-manual-support/

**Comment by delta217** [comment]
OK, j'y suis...
A suivre voir si j'y arrive !

**Comment by delta217** [comment]
J'avance, mais pourquoi ce con de seeyou, sans que comprenne pourquoi, se barre à l'ouest pour 100 km ???

**Comment by delta217** [comment]
Bon.... source tree, c'est pas pour moi, je suis obsolète sur ce coup là !
J'ai utilisé SeeYou pour ajouter des landmarks et quelques sommets dans le secteur Aiguines-Chambeyron jusqu'à la Durance.
J'ai un peu regardé avec meldmerge : compris qu'en bleu, j'avais ouvert, et parfois modifié, une ligne... En jaune, je ne sais pas.
EN PJ, mon fichier modifié en txt pour qu'il passe.
[mountain_peaks_FR_CH_IT_1.txt](https://github.com/planeur-net/outlanding/files/14072871/mountain_peaks_FR_CH_IT_1.txt)
Si tu peux en faire quelquechose ?
Si oui, je peux continuer sur les autres secteurs. Question : possible de voir les #landmark dans SeeYou sans éditer ? Ce serait un gain de temps considérable.
A vous lire, patron...

**Comment by llauner** [comment]
Ah ben la ca va etre complique...tu as modifie le FR_CH_IT = un fichier genere automatiquement.
Bon je vais isoler le FR et regarder si j'arrive a voir les changements...
C'est pas gagne ! :)

**Comment by llauner** [comment]
Je vois qu'il y a des coordonnées qui ont changées, pas grand chose, mais ca a change...c'est normal ?
Parce que la source initiale est normalement fiable...donc....

**Comment by delta217** [comment]
Arghhhh, le prochaine fois (if any ?), je te passe le .cup par un autre biais, de sorte que çà ne foute pas le brin partout...
My apologizes !

**Comment by llauner** [comment]
Oui parce que la on est en train de faire le contraire de ce qu'on veut = 1 personne qui consolide un fichier avec des infos d'une autre personne...
Bon pas grave, j'ajoute les landmark ou tu as ajoute..

**Comment by mlep** [comment]
> Je pense qu'on pourrait lancer un appel pour les noms velivoles

Il faudra préciser ce que l'on appelle "noms vélivoles", sinon, on va se retrouver avec tous les sommets que les gens connaissent. Proposition : `Sommet utilisé habituellement pour annoncer sa position, et grâce auquel les autres pilotes nous localiserons facilement.`

**Comment by delta217** [comment]
Je suis toujours dubitatif sur cette question... Y-en-a-t-il tant que çà ? Authon, Auribeau, OK, et la tête de Lucy (toponymiquement fausse, mais phonétiquement presque juste : tête d'Esclucis). Les "apôtres" sont en voie de disparition... Et puis ? Et d'ailleurs, l'usage des vrais noms serait tout à fait recommandable dans une optique SAR (un planeur crashé sur la Grisonnière vaut mieux qu'un planeur crashé sur l'Ubac, lesquelles sont légion). J'ai découvert un pas de la Cavale tout au nord du Mercantour...

**Comment by llauner** [comment]
Dans le nettoyage pour SeeYou j'ai fait le ménage et j'ai dégagé les homonymes qui du coups n'aident pas à se localiser. Surtout quand ils sont à moins de 10km l'un de l'autre. 
Je te passe donc les têtes blanches, rousses, noires, les aiguillettes, montagnettes, et j'en oublie !

**Comment by mlep** [comment]
Il faut que nous définissions à quoi sert ce fichier.
Pour moi, le fichier sert essentiellement quand on est en l'air et que l'on parle à la radio : Il doit permettre d'annoncer une position qui "parlent" aux autres. Et on ne part pas d'une page blanche : des noms sont utilisés, d'autres non.
Les (nombreuses) homonymes comptent peu en pratique : si tu étais aux Bans et que 20' plus tard, tu t'annonces au Pas de Cavale, zéro chance que tu sois dans le Mercantour.  Et si j'ai un doute, simple : je te demande.
Des exemples de confusion de localisation vélivole qui ont créé un problème pour du SAR ?  (il y a déjà eu un crash sur Authon, on a retrouvé le planeur).
