### ISSUE TITLE
Mountain_peaks_FR: Noms longs et codes

### ISSUE THREAD

**Issue by llauner** [planeur-net/outlanding#58]
Limitation des noms long.
Limitation TRES moderee des nom pour que cela reste lisible instantanement.
Par exemple: Montagne -> Mtgn

Les nom longs restent tres lisibles. Je ne suis pas certain que cette tache soit vraiment utile au final.
A faire apres la dedensification #56

**Comment by mlep** [comment]
Je me posais la question de l'utilité des noms courts.
À mon sens, ils ne nous sont pas utiles : soit tu connais le sommet et tu n'as alors pas besoin qu'il s'affiche, soit tu ne le connais pas et le nom court t'es inutile (car tu as alors besoin du nom long). Du coup, je ne vois pas d'intérêt à travailler sur les noms courts.

**Comment by llauner** [comment]
Limitation des noms longs pas nécessaire.
