### ISSUE TITLE
Altitudes Selonnet

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#6]
Attention, deux champs avec des altitudes différentes
"Selonnet-1",Selont-1,FR,4422.100N,00618.600E,1077.0m,3,40,250m,,"Bleu-30 (Page 154) : Zone posable n°1",,
"Selonnet-2",Selont-2,FR,4420.800N,00619.900E,1126.0m,3,150,300m,,"Bleu-30 (Page 154) : Zone posable N°2",,

**Comment by llauner** [comment]
Correction faite.
Je vais supprimer le meme commentaire dans #4 puisque le guide 4.1 comporte deja les 2 champs.
Une pull request pour la correction la prochaine fois ? :)

**Comment by delta217** [comment]
> Une pull request pour la correction la prochaine fois ? :)

J'ai déjà réussi à éditer une issue, pas tout le même jour quand même !
