### ISSUE TITLE
522 Grisail : Localiser sur geoportail

### ISSUE THREAD

**Issue by llauner** [planeur-net/outlanding#61]
Je n'arrive pas a localiser 522 Grisail sur Geoportail.
Je ne retrouve pas la meme localisation que les images du guide.
Coord dans le guide = 44.950000,005.625000

**Comment by delta217** [comment]
Champ de l'édition 3 
Monte vers le nord de 796 à 822m

![522_Grisail](https://github.com/planeur-net/outlanding/assets/154979750/33f61fb7-7ca7-4a3a-b9bf-3943f22266d2)

**Comment by delta217** [comment]
Le deuxième champs de l'édition 3 

![522_Grisail2](https://github.com/planeur-net/outlanding/assets/154979750/edb799e8-04e0-4a0e-a5dd-47bbedbe2629)

Le champs indiqué par les coordonnées du guide (édition 4?) est un boyau !

**Comment by llauner** [comment]
Merci, je vais ajouter les images corriger les coords.
J'ai ajoute cette modif a communiquer pour la prochaine edition du Guide
