### ISSUE TITLE
Lesche en Diois

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#7]
Une intéressante plate-forme ULM, balisée, à 6km du col de Cabre au 133°. Pour le jour où "çà passe pas"...
Format cup : "Lesches",LF2655,,4435.300N,00532.470E,975.0m,2,337,250.0m,"130.000","0680528747",,

![lesche-en-diois](https://github.com/planeur-net/outlanding/assets/154979750/c6313419-ae03-4e73-aa7e-0e0c4a482546)

**Comment by llauner** [comment]
Merci.
Je te laisse essayer de faire une pull request ?
Tu fais un fork du repo sur ton compte, tu modifies champs_des_alpes.cup, et ensuite pull request vers le repo outlanding.
Tout est faisable depuis l'interface github.

Quel est ton nom ? tu voles ou ?

**Comment by delta217** [comment]
Bonjour Ludovic,

Je vole à Sisteron principalement, un peu à Seyne, et de l'instruction en 2023 à Aspres (Sisteron avait arrêté l'école en 2023 ☹ ). 
J'ai un peu tenté un pull request, mais il faut être bac +7..., ou alors maîtriser un langage qui n'est pas tout à fait du français, et pas tout à fait de l'anglais !
@+ 


_________________
Jean-Philippe Bayart
+33(0)671 93 60 75☹
Le 27/12/2023 17:59:12, Ludovic ***@***.***> a écrit :
Merci.
Je te laisse essayer de faire une pull request ?
Tu fais un fork du repo sur ton compte, tu modifies champs_des_alpes.cup, et ensuite pull request vers le repo outlanding.
Tout est faisable depuis l'interface github.
Quel est ton nom ? tu voles ou ?

**Comment by llauner** [comment]
Je viens d'ajouter Lesche en Diois.
