### ISSUE TITLE
Des commits à se débarasser... 

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#81]
J'ai dégagé mes branches, fait une synchro, mais j'ai toujours des commits ahead, dont le fameux Chauffayer...

![image](https://github.com/planeur-net/outlanding/assets/154979750/afd0df80-705a-442e-8c25-d93d5994c5a8)

**Comment by llauner** [comment]
C'est bon j'ai fait ce qu'il fallait, tu es a jour  maintenant..
