### ISSUE TITLE
Cols des Alpes : décalages, format

### ISSUE THREAD

**Issue by mlep** [planeur-net/outlanding#87]
En regardant les cols des Alpes dans le fichier, j'ai trouvé des décalages notables (mais rien de tragique) :
![ksnip_20240118-114804](https://github.com/planeur-net/outlanding/assets/6931104/3f9649d6-8e44-4a0e-9137-287ca3b2ab42)
![ksnip_20240118-114805](https://github.com/planeur-net/outlanding/assets/6931104/5d95584e-50e6-4a4a-9ece-a1db06cead54)
![ksnip_20240118-114806](https://github.com/planeur-net/outlanding/assets/6931104/54fd556d-2a33-40a3-8d18-82f7d6a216ef)

Du coup, je me suis posé la question de la source de ce fichier ; et de savoir s'il fallait corriger à la main.

Et aussi j'ai vu que le format était un peu différent par rapport au fichier des sommets. Par ex, dans
`"C-Faucil",,FR,4622.166N,00601.116E,1320.0m,6,,,,,"{col} de la faucil",,` :
- nom raccourci dans la première colonne (pourquoi pas le nom complet ?)
- pas de nom raccourci dans la 2nd colonne (?)
- description avec un format particulier et un nom court (ex : {col} sud usine ri)

**Comment by llauner** [comment]
La source..c'est moi...ou plutôt je l'ai récupéré de je ne sais plus ou et c'est vrai que maintenant que tu le dis...il aurait besoin d'être un peu rafraichi.
je suis bien d'accord qu'il faudrait le normaliser avec le reste.
1) La premiere colonne devrait etre le nom complet. Par contre j'aime bien la notation C-xxx ca permet de voir et de chercher rapidement dans XCSoar / SeeYou Navigator. Je m'en sert tres souvent.

2)  La deuxieme devrait contenir un nom court

3) Il y a {col} dans la description comme il y a {facile} ou {difficile} afin d'associer le bon icone dans le format kmz. Je propose de garder ce tag, mais du coups apres que 1) et 2)  soient fait, il n'y a plus lieu d'avoir autre chose dans la description car le nom long sera le bon...

4) Il faut ajouter le pays pour certains cols. Il manque.

Questions:
On fait quoi avec les: du, de la, ...
Col du Tourniol c'est C-Tourniol ou C- Du Tourniol ?

**Comment by mlep** [comment]
>     1. La premiere colonne devrait etre le nom complet. Par contre j'aime bien la notation C-xxx ca permet de voir et de chercher rapidement dans XCSoar / SeeYou Navigator. Je m'en sert tres souvent.

Et si l'on mettait le nom long dans la 1ère colonne et C-xxx comme nom court ?

>     3. Il y a {col} dans la description comme il y a {facile} ou {difficile} afin d'associer le bon icone dans le format kmz. Je propose de garder ce tag, mais du coups apres que 1) et 2)  soient fait, il n'y a plus lieu d'avoir autre chose dans la description car le nom long sera le bon...

On verra plus tard alors.

>     4. Il faut ajouter le pays pour certains cols. Il manque.

Ce ne sont pas les cols frontaliers ? (avec un --)
Et dans ce cas, je ne vois pas bien mieux.

>     5. Si le col est pas bien localiser, on peut (doit) changer pour mettre les bonnes coords.

OK, à faire.


> Questions: On fait quoi avec les: du, de la, ... Col du Tourniol c'est C-Tourniol ou C- Du Tourniol ?

Si le symbole suffit, "Tourniol". Mais le symbole suffit-il ?...
On a un peu la même question pour les sommets... et pas facile de répondre.

**Comment by llauner** [comment]
> Et si l'on mettait le nom long dans la 1ère colonne et C-xxx comme nom court ?

Pourquoi pas. On a bien le nom (tres) long pour le reste

> > 3. Il y a {col} dans la description comme il y a {facile} ou {difficile} afin d'associer le bon icone dans le format kmz. Je propose de garder ce tag, mais du coups apres que 1) et 2)  soient fait, il n'y a plus lieu d'avoir autre chose dans la description car le nom long sera le bon...

> On verra plus tard alors.

Ah mais je viens de voir qu'il y avait des bug avec un {col} dans le nom long: C-For{col} c'est n'importe quoi... on sait meme pas quel col c'est...faut regarder et corriger..



> Ce ne sont pas les cols frontaliers ? (avec un --) Et dans ce cas, je ne vois pas bien mieux.

J'ai pas l'impression...la Furka par exemple c'est pas frontalier.


> Si le symbole suffit, "Tourniol". Mais le symbole suffit-il ?... On a un peu la même question pour les sommets... et pas facile de répondre.
Ca ferait
Col du Tourniol, C-Tourniol
Allez...on peut faire comme ca.
Pour filtrer ca fait le meme nombre de "clicks" pour faire C- ou col donc essayons comme ca.

**Comment by llauner** [comment]
Je suis dessus...j'en suis a 31/120...

**Comment by mlep** [comment]
Merci pour le gros reformatage.
Yapluka nettoyer, améliorer, etc. Bref, de la maintenance.
