### ISSUE TITLE
Commits ahead

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#91]
Pourquoi j'ai des vieux zinzins qui reviennent dans mes commits ahead ???

![image](https://github.com/planeur-net/outlanding/assets/154979750/f4844748-6e54-471b-aa8e-00522211a7e8)

**Comment by llauner** [comment]
La t'es 1 commit ahead,. Tu as du changer un truc et faire un commit par rapport a ce qui est sur planeur-net
Avant que la PR soit mergee c'est normal que tu sois xx commit ahead sur une branch

**Comment by llauner** [comment]
Non t'es comme ca sur main:
![image](https://github.com/planeur-net/outlanding/assets/32835597/2b7f323a-6921-4915-9b8e-bcead7996f52)

**Comment by llauner** [comment]
Je peux te faire un petit reset des familles si tu veux :)
J'ai pas trop cherche a comprendre ce que tu as fait pour te retrouver dans cette situation, mais je suppose que ca doit etre une branche depuis une branche ou un truc qui a ete merge avec master...je sais pas :)

**Comment by delta217** [comment]
Ben  non ?

![image](https://github.com/planeur-net/outlanding/assets/154979750/708d93b3-b143-4fcb-a410-931d9a996082)

Fais moi donc un cleaning...

**Comment by llauner** [comment]
C'est fait
