### ISSUE TITLE
les cols FR ?

### ISSUE THREAD

**Issue by delta217** [planeur-net/outlanding#93]
Je suis perdu au niveau des cols...
Dans mountain peaks FR CH IT, il y a plein de cols, mais presque tous en Italie.
Et 3 ou 4 en France (Forclaz...)
Correct ?

**Comment by delta217** [comment]
Et je confirme que le fichier col des alpes est assez approximatif :
 
![image](https://github.com/planeur-net/outlanding/assets/154979750/26ec7905-c549-4b15-b899-c29800d23283)

J'ai commencé à corriger dans seeyou.

**Comment by mlep** [comment]
Euh, moi aussi...

**Comment by llauner** [comment]
> Je suis perdu au niveau des cols... Dans mountain peaks FR CH IT, il y a plein de cols, mais presque tous en Italie. Et 3 ou 4 en France (Forclaz...) Correct ?

Oui...c'est le cas. Je sais pas si c'est une bonne chose ou non mais pour FR on a bien séparé, pour CH et IT on a recupere comme c'etait. Je pense qu'on peut laisser pour le moment, sinon ca va multiplier les fichiers.

Par contre si il y a des cols FR dans se fichier, il faut les virer de mountain_peaks_FR et les ajouter si ils n'y sont pas dans cols_des_alpes.cup
Mais standby...a faire quand la pull de @mlep est passée

**Comment by llauner** [comment]
> Euh, moi aussi : PR #94 @delta217 : si tu veux faire une review, c'est dans la PR

Je viens de vous donner les droits "Triage", je pense que vous devriez maintenant pouvoir vous assigner une Issue.
Pour ne pas faire 2 fois la meme chose en parallèle, pensez a vous assigner l'issue comme ca on voit que quelqu'un est sur le coup.
Cerise sur le gateau, si vous ajoutez le numero de l'issue dans votre dernier commit (#xx), l'issue passe automatiquement en "resolved" magique :)

**Comment by llauner** [comment]
Bon je pense que j'ai reconcilie les cols_des_alpes...
